# Generated by Django 5.2 on 2025-04-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_historicosaude_delete_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicosaude',
            name='alergias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicosaude',
            name='convenio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicosaude',
            name='motivo_da_consulta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicosaude',
            name='possui_doencas_cronicas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicosaude',
            name='uso_medicamentos',
            field=models.TextField(blank=True),
        ),
    ]
