# Generated by Django 5.2 on 2025-04-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_historicosaude_alergias_historicosaude_convenio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicosaude',
            name='ultima_consulta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
