# Generated by Django 5.2 on 2025-04-17 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_historicosaude_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('texto', 'Texto Curto'), ('texto_longo', 'Texto Longo'), ('sim_nao', 'Sim/Não')], max_length=20)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='agenda.formulariopersonalizado')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
                ('respondido_em', models.DateTimeField(auto_now_add=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.campoformulario')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='agenda.formulariopersonalizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_formularios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
